[NAE-1721] Create case event bad handling on frontend
netgrif/components pull request #108
Opened 2022-09-15 12:11 UTC by Kovy95

# Description
- handle error

Implements [NAE-1721]

## Dependencies
none

### Third party dependencies
No new dependencies were introduced

### Blocking Pull requests
There are no dependencies on other PR

## How Has Been This Tested?
manually

### Test Configuration

| Name                | Tested on |
|---------------------| --------- |
| OS                  |     Linux Mint      |
| Runtime             |     NodeJS     |
| Dependency Manager  |     NPM      |
| Framework version   |     Andular 13.2      |
| Run parameters      |           |
| Other configuration |           |

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My changes have been checked, personally or remotely, with @...
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have resolved all conflicts with the target branch of the PR
- [x] I have updated and synced my code with the target branch
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes:
    - [x] Lint test
    - [x] Unit tests
    - [x] Integration tests
- [ ] I have checked my contribution with code analysis tools:
    - [ ] [SonarCloud](https://sonarcloud.io/project/overview?id=netgrif_components)
    - [ ] [Snyk](https://app.snyk.io/org/netgrif)
- [x] I have made corresponding changes to the documentation:
    - [x] Developer documentation
    - [x] User Guides
    - [x] Migration Guides

2022-09-21 08:51 UTC, machacjozef commented on projects/netgrif-components-core/src/assets/i18n/en.json
> +            "createCaseError": "New case created, but an error occurred while executing actions"
New case was created, but an error occurred while executing actions

maybe: 
A new case was created, but an error occurred while executing actions


by @minop

2022-09-21 08:51 UTC, machacjozef commented on projects/netgrif-components-core/src/assets/i18n/de.json
> +            "createCaseError": "Neuer Fall erstellt, aber beim Ausführen von Aktionen ist ein Fehler aufgetreten"
Neuer Fall wurde erstellt, aber beim Ausführen von Aktionen ist ein Fehler aufgetreten



by @minop

2022-09-21 12:26 UTC, minop requested changes

2022-09-21 12:26 UTC, minop commented on projects/netgrif-components-core/src/assets/i18n/sk.json
> +            "createCaseError": "Nový prípad vytvorený, nastala však chyba pri vykonávanií akcií"
vykonávaní

2022-09-21 12:52 UTC, Kovy95 commented on projects/netgrif-components-core/src/assets/i18n/sk.json
> +            "createCaseError": "Nový prípad vytvorený, nastala však chyba pri vykonávanií akcií"
done

2022-09-26 12:59 UTC, minop approved these changes

2022-09-26 16:45 UTC, mladoniczky approved these changes

2022-09-27 13:19 UTC, merged