Nae 1571
netgrif/components pull request #18
Opened 2022-03-07 08:10 UTC by renczesstefan

- refactored newest version string

# Description

When you search for a specific PetriNet by the newest version, as a version parameter the "^” string is used. However, if we are using this in cloud, and there are rewrite rules for the request path, engine will throw an error as the URL contains invalid characters.
Solution was replacing of newest version string to "latest".

Implements [NAE-1571]

## Dependencies

No new dependencies were introduced.

### Third party dependencies

No new dependencies were introduced.

### Blocking Pull requests

There are no dependencies on other PR.

## How Has Been This Tested?

This was tested manually, checked in developer tools of Google Chrome and via application functionality.

### Test Configuration

This was tested on macOS Monterey 12.2.1 with Node 12.22.10 and NPM 6.14.16

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes have been checked, personally or remotely, with @mladoniczky 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have resolved all conflicts with the target branch of the PR
- [x] I have updated and synced my code with the target branch
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes:
    - [ ] Lint test
    - [ ] Unit tests
    - [ ] Integration tests
- [ ] I have checked my contribution with code analysis tools:
    - [ ] [SonarCloud](https://sonarcloud.io/project/overview?id=netgrif_application-engine)
    - [ ] [Snyk](https://app.snyk.io/org/netgrif/project/ea82b3b8-658d-41f5-89a7-76cd600da01f)
- [x] I have made corresponding changes to the documentation:
    - [x] Developer documentation
    - [x] User Guides
    - [ ] Migration Guides

2022-03-07 18:51 UTC, minop commented
please update the development branch with the current version of the release branch, so that only the changes made in this dev branch are shown in the PR.

2022-03-10 14:37 UTC, mladoniczky requested changes

2022-03-23 08:45 UTC, minop submitted a review, later dismissed

2022-03-25 10:22 UTC, minop requested changes

2022-03-25 10:22 UTC, minop commented on projects/netgrif-components-core/src/lib/process/process.service.ts
> +    protected readonly LATEST = 'latest';
the constant should be public, so that it can be referenced outside of the class if necessary

2022-03-25 10:33 UTC, minop submitted a review, later dismissed

2022-03-25 11:22 UTC, renczesstefan commented on projects/netgrif-components-core/src/lib/process/process.service.ts
> +        this._petriNetResource.getOne(id, 'latest').subscribe(reference => {
Done

2022-03-28 14:54 UTC, machacjozef approved these changes

2022-03-28 15:00 UTC, mladoniczky submitted a review, later dismissed

2022-03-28 15:32 UTC, machacjozef approved these changes

2022-03-28 16:21 UTC, mladoniczky approved these changes

2022-03-28 16:38 UTC, merged