[NAE-1597] New case process input is not validated
netgrif/components pull request #36
Opened 2022-04-07 08:48 UTC by machacjozef

# Description

 - resolve Parent Task Id
 
Fixes [NAE-1597]

## Dependencies

No new dependencies were introduced

### Third party dependencies

No new dependencies were introduced

### Blocking Pull requests

There are no dependencies on other PR.

| Name                | Tested on |
|---------------------| --------- |
| OS                  |      Linux Mint 20.3     |
| Runtime             |  Node v12.22.11         |
| Dependency Manager  |   NPM 6.14.16      |
| Framework version   |    Angular 10.2.3       |
| Run parameters      |           |
| Other configuration |           |

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes have been checked, personally or remotely, with @...
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have resolved all conflicts with the target branch of the PR
- [x] I have updated and synced my code with the target branch
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes:
    - [x] Lint test
    - [x] Unit tests
    - [x] Integration tests
- [x] I have checked my contribution with code analysis tools:
    - [x] [SonarCloud](https://sonarcloud.io/project/overview?id=netgrif_application-engine)
    - [x] [Snyk](https://app.snyk.io/org/netgrif)
- [x] I have made corresponding changes to the documentation:
    - [x] Developer documentation
    - [x] User Guides
    - [x] Migration Guides

2022-04-07 10:22 UTC, minop requested changes

2022-04-07 10:22 UTC, minop commented on projects/netgrif-components-core/src/lib/side-menu/content-components/new-case/abstract-new-case.component.ts
> +        if (viewValue !== null && viewValue.value !== undefined) {
this does not solve the case when a value is written into the autocomplete input that matches none of the options.

a unit test should be added to check if the method performs as intended

2022-04-07 10:47 UTC, minop commented on projects/netgrif-components-core/src/lib/side-menu/content-components/new-case/abstract-new-case.component.ts
> +        if (viewValue !== null && viewValue.value !== undefined) {
resolved in a personal call

2022-04-07 10:47 UTC, minop approved these changes

2022-04-08 10:29 UTC, renczesstefan approved these changes

2022-04-08 11:13 UTC, merged