[Nae 1631] Process download in workflow view
netgrif/components pull request #57
Opened 2022-05-17 11:39 UTC by Daniell7

# Description

Add button to download xml file from workflow view

Implements [NAE 1631]

## Dependencies

No new dependencies

### Third party dependencies

No new dependencies were introduced

### Blocking Pull requests

There are no dependencies on other PR

## How Has Been This Tested?

Assisted testing + manual testing

### Test Configuration

| Name                | Tested on |
|---------------------| --------- |
| OS                  | Windows 10 |
| Runtime             | Node 12.18.3 |
| Dependency Manager  | NPM 6.14.6 |
| Framework version   | Angular 10 |
| Run parameters      |           |
| Other configuration |           |

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes have been checked, personally or remotely, with @...
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have resolved all conflicts with the target branch of the PR
- [ ] I have updated and synced my code with the target branch
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes:
    - [ ] Lint test
    - [ ] Unit tests
    - [ ] Integration tests
- [ ] I have checked my contribution with code analysis tools:
    - [ ] [SonarCloud](https://sonarcloud.io/project/overview?id=netgrif_application-engine)
    - [ ] [Snyk](https://app.snyk.io/org/netgrif)
- [ ] I have made corresponding changes to the documentation:
    - [ ] Developer documentation
    - [ ] User Guides
    - [ ] Migration Guides

2022-05-18 12:52 UTC, minop requested changes

2022-05-18 12:52 UTC, minop commented on projects/netgrif-components-core/src/assets/i18n/de.json
> +        "download": "heruntergeladen",
the verb should not be in the past tense. The correct translation is `herunterladen`

2022-05-23 13:50 UTC, minop submitted a review, later dismissed

2022-08-26 10:43 UTC, mladoniczky submitted a review, later dismissed

2022-09-05 13:23 UTC, mladoniczky approved these changes

2022-09-05 13:41 UTC, merged